markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/bmad/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/bmad/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/bmad/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/bmad/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/bmad/architecture/coding-standards.md
  - docs/bmad/architecture/tech-stack.md
  - docs/bmad/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/bmad/stories
slashPrefix: BMad
